/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125QualifikationRouteImport } from './routes/{-$locale}/qualifikation'
import { Route as Char123LocaleChar125PraxisRouteImport } from './routes/{-$locale}/praxis'
import { Route as Char123LocaleChar125LeistungenRouteImport } from './routes/{-$locale}/leistungen'
import { Route as Char123LocaleChar125KontaktRouteImport } from './routes/{-$locale}/kontakt'
import { Route as Char123LocaleChar125KarriereRouteImport } from './routes/{-$locale}/karriere'
import { Route as Char123LocaleChar125ImpressumRouteImport } from './routes/{-$locale}/impressum'
import { Route as Char123LocaleChar125DatenschutzRouteImport } from './routes/{-$locale}/datenschutz'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as ApiFileUploadsRouteImport } from './routes/api/file-uploads'
import { Route as Char123LocaleChar125AdminIndexRouteImport } from './routes/{-$locale}/admin/index'
import { Route as Char123LocaleChar125AdminVisitorChatsRouteImport } from './routes/{-$locale}/admin/visitor-chats'
import { Route as Char123LocaleChar125AdminVacationsRouteImport } from './routes/{-$locale}/admin/vacations'
import { Route as Char123LocaleChar125AdminChatRouteImport } from './routes/{-$locale}/admin/chat'
import { Route as ApiFileUploadsFileUploadIdRouteImport } from './routes/api/file-uploads_.$fileUploadId'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125QualifikationRoute =
  Char123LocaleChar125QualifikationRouteImport.update({
    id: '/qualifikation',
    path: '/qualifikation',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PraxisRoute =
  Char123LocaleChar125PraxisRouteImport.update({
    id: '/praxis',
    path: '/praxis',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125LeistungenRoute =
  Char123LocaleChar125LeistungenRouteImport.update({
    id: '/leistungen',
    path: '/leistungen',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125KontaktRoute =
  Char123LocaleChar125KontaktRouteImport.update({
    id: '/kontakt',
    path: '/kontakt',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125KarriereRoute =
  Char123LocaleChar125KarriereRouteImport.update({
    id: '/karriere',
    path: '/karriere',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ImpressumRoute =
  Char123LocaleChar125ImpressumRouteImport.update({
    id: '/impressum',
    path: '/impressum',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125DatenschutzRoute =
  Char123LocaleChar125DatenschutzRouteImport.update({
    id: '/datenschutz',
    path: '/datenschutz',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsRoute = ApiFileUploadsRouteImport.update({
  id: '/api/file-uploads',
  path: '/api/file-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AdminIndexRoute =
  Char123LocaleChar125AdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AdminVisitorChatsRoute =
  Char123LocaleChar125AdminVisitorChatsRouteImport.update({
    id: '/admin/visitor-chats',
    path: '/admin/visitor-chats',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AdminVacationsRoute =
  Char123LocaleChar125AdminVacationsRouteImport.update({
    id: '/admin/vacations',
    path: '/admin/vacations',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AdminChatRoute =
  Char123LocaleChar125AdminChatRouteImport.update({
    id: '/admin/chat',
    path: '/admin/chat',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiFileUploadsFileUploadIdRoute =
  ApiFileUploadsFileUploadIdRouteImport.update({
    id: '/api/file-uploads_/$fileUploadId',
    path: '/api/file-uploads/$fileUploadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/karriere': typeof Char123LocaleChar125KarriereRoute
  '/{-$locale}/kontakt': typeof Char123LocaleChar125KontaktRoute
  '/{-$locale}/leistungen': typeof Char123LocaleChar125LeistungenRoute
  '/{-$locale}/praxis': typeof Char123LocaleChar125PraxisRoute
  '/{-$locale}/qualifikation': typeof Char123LocaleChar125QualifikationRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/admin/chat': typeof Char123LocaleChar125AdminChatRoute
  '/{-$locale}/admin/vacations': typeof Char123LocaleChar125AdminVacationsRoute
  '/{-$locale}/admin/visitor-chats': typeof Char123LocaleChar125AdminVisitorChatsRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/karriere': typeof Char123LocaleChar125KarriereRoute
  '/{-$locale}/kontakt': typeof Char123LocaleChar125KontaktRoute
  '/{-$locale}/leistungen': typeof Char123LocaleChar125LeistungenRoute
  '/{-$locale}/praxis': typeof Char123LocaleChar125PraxisRoute
  '/{-$locale}/qualifikation': typeof Char123LocaleChar125QualifikationRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/admin/chat': typeof Char123LocaleChar125AdminChatRoute
  '/{-$locale}/admin/vacations': typeof Char123LocaleChar125AdminVacationsRoute
  '/{-$locale}/admin/visitor-chats': typeof Char123LocaleChar125AdminVisitorChatsRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/datenschutz': typeof Char123LocaleChar125DatenschutzRoute
  '/{-$locale}/impressum': typeof Char123LocaleChar125ImpressumRoute
  '/{-$locale}/karriere': typeof Char123LocaleChar125KarriereRoute
  '/{-$locale}/kontakt': typeof Char123LocaleChar125KontaktRoute
  '/{-$locale}/leistungen': typeof Char123LocaleChar125LeistungenRoute
  '/{-$locale}/praxis': typeof Char123LocaleChar125PraxisRoute
  '/{-$locale}/qualifikation': typeof Char123LocaleChar125QualifikationRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads_/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
  '/{-$locale}/admin/chat': typeof Char123LocaleChar125AdminChatRoute
  '/{-$locale}/admin/vacations': typeof Char123LocaleChar125AdminVacationsRoute
  '/{-$locale}/admin/visitor-chats': typeof Char123LocaleChar125AdminVisitorChatsRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/karriere'
    | '/{-$locale}/kontakt'
    | '/{-$locale}/leistungen'
    | '/{-$locale}/praxis'
    | '/{-$locale}/qualifikation'
    | '/{-$locale}/'
    | '/api/file-uploads/$fileUploadId'
    | '/{-$locale}/admin/chat'
    | '/{-$locale}/admin/vacations'
    | '/{-$locale}/admin/visitor-chats'
    | '/{-$locale}/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/karriere'
    | '/{-$locale}/kontakt'
    | '/{-$locale}/leistungen'
    | '/{-$locale}/praxis'
    | '/{-$locale}/qualifikation'
    | '/{-$locale}'
    | '/api/file-uploads/$fileUploadId'
    | '/{-$locale}/admin/chat'
    | '/{-$locale}/admin/vacations'
    | '/{-$locale}/admin/visitor-chats'
    | '/{-$locale}/admin'
  id:
    | '__root__'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/datenschutz'
    | '/{-$locale}/impressum'
    | '/{-$locale}/karriere'
    | '/{-$locale}/kontakt'
    | '/{-$locale}/leistungen'
    | '/{-$locale}/praxis'
    | '/{-$locale}/qualifikation'
    | '/{-$locale}/'
    | '/api/file-uploads_/$fileUploadId'
    | '/{-$locale}/admin/chat'
    | '/{-$locale}/admin/vacations'
    | '/{-$locale}/admin/visitor-chats'
    | '/{-$locale}/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiFileUploadsRoute: typeof ApiFileUploadsRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiFileUploadsFileUploadIdRoute: typeof ApiFileUploadsFileUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/qualifikation': {
      id: '/{-$locale}/qualifikation'
      path: '/qualifikation'
      fullPath: '/{-$locale}/qualifikation'
      preLoaderRoute: typeof Char123LocaleChar125QualifikationRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/praxis': {
      id: '/{-$locale}/praxis'
      path: '/praxis'
      fullPath: '/{-$locale}/praxis'
      preLoaderRoute: typeof Char123LocaleChar125PraxisRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/leistungen': {
      id: '/{-$locale}/leistungen'
      path: '/leistungen'
      fullPath: '/{-$locale}/leistungen'
      preLoaderRoute: typeof Char123LocaleChar125LeistungenRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/kontakt': {
      id: '/{-$locale}/kontakt'
      path: '/kontakt'
      fullPath: '/{-$locale}/kontakt'
      preLoaderRoute: typeof Char123LocaleChar125KontaktRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/karriere': {
      id: '/{-$locale}/karriere'
      path: '/karriere'
      fullPath: '/{-$locale}/karriere'
      preLoaderRoute: typeof Char123LocaleChar125KarriereRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/impressum': {
      id: '/{-$locale}/impressum'
      path: '/impressum'
      fullPath: '/{-$locale}/impressum'
      preLoaderRoute: typeof Char123LocaleChar125ImpressumRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/datenschutz': {
      id: '/{-$locale}/datenschutz'
      path: '/datenschutz'
      fullPath: '/{-$locale}/datenschutz'
      preLoaderRoute: typeof Char123LocaleChar125DatenschutzRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads': {
      id: '/api/file-uploads'
      path: '/api/file-uploads'
      fullPath: '/api/file-uploads'
      preLoaderRoute: typeof ApiFileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/admin/': {
      id: '/{-$locale}/admin/'
      path: '/admin'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125AdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/admin/visitor-chats': {
      id: '/{-$locale}/admin/visitor-chats'
      path: '/admin/visitor-chats'
      fullPath: '/{-$locale}/admin/visitor-chats'
      preLoaderRoute: typeof Char123LocaleChar125AdminVisitorChatsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/admin/vacations': {
      id: '/{-$locale}/admin/vacations'
      path: '/admin/vacations'
      fullPath: '/{-$locale}/admin/vacations'
      preLoaderRoute: typeof Char123LocaleChar125AdminVacationsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/admin/chat': {
      id: '/{-$locale}/admin/chat'
      path: '/admin/chat'
      fullPath: '/{-$locale}/admin/chat'
      preLoaderRoute: typeof Char123LocaleChar125AdminChatRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/file-uploads_/$fileUploadId': {
      id: '/api/file-uploads_/$fileUploadId'
      path: '/api/file-uploads/$fileUploadId'
      fullPath: '/api/file-uploads/$fileUploadId'
      preLoaderRoute: typeof ApiFileUploadsFileUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125DatenschutzRoute: typeof Char123LocaleChar125DatenschutzRoute
  Char123LocaleChar125ImpressumRoute: typeof Char123LocaleChar125ImpressumRoute
  Char123LocaleChar125KarriereRoute: typeof Char123LocaleChar125KarriereRoute
  Char123LocaleChar125KontaktRoute: typeof Char123LocaleChar125KontaktRoute
  Char123LocaleChar125LeistungenRoute: typeof Char123LocaleChar125LeistungenRoute
  Char123LocaleChar125PraxisRoute: typeof Char123LocaleChar125PraxisRoute
  Char123LocaleChar125QualifikationRoute: typeof Char123LocaleChar125QualifikationRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125AdminChatRoute: typeof Char123LocaleChar125AdminChatRoute
  Char123LocaleChar125AdminVacationsRoute: typeof Char123LocaleChar125AdminVacationsRoute
  Char123LocaleChar125AdminVisitorChatsRoute: typeof Char123LocaleChar125AdminVisitorChatsRoute
  Char123LocaleChar125AdminIndexRoute: typeof Char123LocaleChar125AdminIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125DatenschutzRoute: Char123LocaleChar125DatenschutzRoute,
  Char123LocaleChar125ImpressumRoute: Char123LocaleChar125ImpressumRoute,
  Char123LocaleChar125KarriereRoute: Char123LocaleChar125KarriereRoute,
  Char123LocaleChar125KontaktRoute: Char123LocaleChar125KontaktRoute,
  Char123LocaleChar125LeistungenRoute: Char123LocaleChar125LeistungenRoute,
  Char123LocaleChar125PraxisRoute: Char123LocaleChar125PraxisRoute,
  Char123LocaleChar125QualifikationRoute:
    Char123LocaleChar125QualifikationRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125AdminChatRoute: Char123LocaleChar125AdminChatRoute,
  Char123LocaleChar125AdminVacationsRoute:
    Char123LocaleChar125AdminVacationsRoute,
  Char123LocaleChar125AdminVisitorChatsRoute:
    Char123LocaleChar125AdminVisitorChatsRoute,
  Char123LocaleChar125AdminIndexRoute: Char123LocaleChar125AdminIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiFileUploadsRoute: ApiFileUploadsRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiFileUploadsFileUploadIdRoute: ApiFileUploadsFileUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
