/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TherapeutinRouteImport } from './routes/{-$locale}/therapeutin'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125PraxisRouteImport } from './routes/{-$locale}/praxis'
import { Route as Char123LocaleChar125PodologieUrkundeRouteImport } from './routes/{-$locale}/podologie-urkunde'
import { Route as Char123LocaleChar125PodologieRouteImport } from './routes/{-$locale}/podologie'
import { Route as Char123LocaleChar125LeistungenRouteImport } from './routes/{-$locale}/leistungen'
import { Route as Char123LocaleChar125KontaktRouteImport } from './routes/{-$locale}/kontakt'
import { Route as Char123LocaleChar125HygieneRouteImport } from './routes/{-$locale}/hygiene'
import { Route as Char123LocaleChar125HeilpraktikerUrkundeRouteImport } from './routes/{-$locale}/heilpraktiker-urkunde'
import { Route as Char123LocaleChar125HeilpraktikerPodologieRouteImport } from './routes/{-$locale}/heilpraktiker-podologie'
import { Route as Char123LocaleChar125ChatRouteImport } from './routes/{-$locale}/chat'
import { Route as Char123LocaleChar125AnfahrtRouteImport } from './routes/{-$locale}/anfahrt'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as ApiFileUploadsRouteImport } from './routes/api/file-uploads'
import { Route as ApiFileUploadsFileUploadIdRouteImport } from './routes/api/file-uploads_.$fileUploadId'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TherapeutinRoute =
  Char123LocaleChar125TherapeutinRouteImport.update({
    id: '/therapeutin',
    path: '/therapeutin',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PraxisRoute =
  Char123LocaleChar125PraxisRouteImport.update({
    id: '/praxis',
    path: '/praxis',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PodologieUrkundeRoute =
  Char123LocaleChar125PodologieUrkundeRouteImport.update({
    id: '/podologie-urkunde',
    path: '/podologie-urkunde',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PodologieRoute =
  Char123LocaleChar125PodologieRouteImport.update({
    id: '/podologie',
    path: '/podologie',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125LeistungenRoute =
  Char123LocaleChar125LeistungenRouteImport.update({
    id: '/leistungen',
    path: '/leistungen',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125KontaktRoute =
  Char123LocaleChar125KontaktRouteImport.update({
    id: '/kontakt',
    path: '/kontakt',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125HygieneRoute =
  Char123LocaleChar125HygieneRouteImport.update({
    id: '/hygiene',
    path: '/hygiene',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125HeilpraktikerUrkundeRoute =
  Char123LocaleChar125HeilpraktikerUrkundeRouteImport.update({
    id: '/heilpraktiker-urkunde',
    path: '/heilpraktiker-urkunde',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125HeilpraktikerPodologieRoute =
  Char123LocaleChar125HeilpraktikerPodologieRouteImport.update({
    id: '/heilpraktiker-podologie',
    path: '/heilpraktiker-podologie',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ChatRoute =
  Char123LocaleChar125ChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AnfahrtRoute =
  Char123LocaleChar125AnfahrtRouteImport.update({
    id: '/anfahrt',
    path: '/anfahrt',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsRoute = ApiFileUploadsRouteImport.update({
  id: '/api/file-uploads',
  path: '/api/file-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsFileUploadIdRoute =
  ApiFileUploadsFileUploadIdRouteImport.update({
    id: '/api/file-uploads_/$fileUploadId',
    path: '/api/file-uploads/$fileUploadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/anfahrt': typeof Char123LocaleChar125AnfahrtRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/heilpraktiker-podologie': typeof Char123LocaleChar125HeilpraktikerPodologieRoute
  '/{-$locale}/heilpraktiker-urkunde': typeof Char123LocaleChar125HeilpraktikerUrkundeRoute
  '/{-$locale}/hygiene': typeof Char123LocaleChar125HygieneRoute
  '/{-$locale}/kontakt': typeof Char123LocaleChar125KontaktRoute
  '/{-$locale}/leistungen': typeof Char123LocaleChar125LeistungenRoute
  '/{-$locale}/podologie': typeof Char123LocaleChar125PodologieRoute
  '/{-$locale}/podologie-urkunde': typeof Char123LocaleChar125PodologieUrkundeRoute
  '/{-$locale}/praxis': typeof Char123LocaleChar125PraxisRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/therapeutin': typeof Char123LocaleChar125TherapeutinRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/anfahrt': typeof Char123LocaleChar125AnfahrtRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/heilpraktiker-podologie': typeof Char123LocaleChar125HeilpraktikerPodologieRoute
  '/{-$locale}/heilpraktiker-urkunde': typeof Char123LocaleChar125HeilpraktikerUrkundeRoute
  '/{-$locale}/hygiene': typeof Char123LocaleChar125HygieneRoute
  '/{-$locale}/kontakt': typeof Char123LocaleChar125KontaktRoute
  '/{-$locale}/leistungen': typeof Char123LocaleChar125LeistungenRoute
  '/{-$locale}/podologie': typeof Char123LocaleChar125PodologieRoute
  '/{-$locale}/podologie-urkunde': typeof Char123LocaleChar125PodologieUrkundeRoute
  '/{-$locale}/praxis': typeof Char123LocaleChar125PraxisRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/therapeutin': typeof Char123LocaleChar125TherapeutinRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/anfahrt': typeof Char123LocaleChar125AnfahrtRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/heilpraktiker-podologie': typeof Char123LocaleChar125HeilpraktikerPodologieRoute
  '/{-$locale}/heilpraktiker-urkunde': typeof Char123LocaleChar125HeilpraktikerUrkundeRoute
  '/{-$locale}/hygiene': typeof Char123LocaleChar125HygieneRoute
  '/{-$locale}/kontakt': typeof Char123LocaleChar125KontaktRoute
  '/{-$locale}/leistungen': typeof Char123LocaleChar125LeistungenRoute
  '/{-$locale}/podologie': typeof Char123LocaleChar125PodologieRoute
  '/{-$locale}/podologie-urkunde': typeof Char123LocaleChar125PodologieUrkundeRoute
  '/{-$locale}/praxis': typeof Char123LocaleChar125PraxisRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/therapeutin': typeof Char123LocaleChar125TherapeutinRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads_/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/anfahrt'
    | '/{-$locale}/chat'
    | '/{-$locale}/heilpraktiker-podologie'
    | '/{-$locale}/heilpraktiker-urkunde'
    | '/{-$locale}/hygiene'
    | '/{-$locale}/kontakt'
    | '/{-$locale}/leistungen'
    | '/{-$locale}/podologie'
    | '/{-$locale}/podologie-urkunde'
    | '/{-$locale}/praxis'
    | '/{-$locale}/terms'
    | '/{-$locale}/therapeutin'
    | '/{-$locale}/'
    | '/api/file-uploads/$fileUploadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/anfahrt'
    | '/{-$locale}/chat'
    | '/{-$locale}/heilpraktiker-podologie'
    | '/{-$locale}/heilpraktiker-urkunde'
    | '/{-$locale}/hygiene'
    | '/{-$locale}/kontakt'
    | '/{-$locale}/leistungen'
    | '/{-$locale}/podologie'
    | '/{-$locale}/podologie-urkunde'
    | '/{-$locale}/praxis'
    | '/{-$locale}/terms'
    | '/{-$locale}/therapeutin'
    | '/{-$locale}'
    | '/api/file-uploads/$fileUploadId'
  id:
    | '__root__'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/anfahrt'
    | '/{-$locale}/chat'
    | '/{-$locale}/heilpraktiker-podologie'
    | '/{-$locale}/heilpraktiker-urkunde'
    | '/{-$locale}/hygiene'
    | '/{-$locale}/kontakt'
    | '/{-$locale}/leistungen'
    | '/{-$locale}/podologie'
    | '/{-$locale}/podologie-urkunde'
    | '/{-$locale}/praxis'
    | '/{-$locale}/terms'
    | '/{-$locale}/therapeutin'
    | '/{-$locale}/'
    | '/api/file-uploads_/$fileUploadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiFileUploadsRoute: typeof ApiFileUploadsRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiFileUploadsFileUploadIdRoute: typeof ApiFileUploadsFileUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/therapeutin': {
      id: '/{-$locale}/therapeutin'
      path: '/therapeutin'
      fullPath: '/{-$locale}/therapeutin'
      preLoaderRoute: typeof Char123LocaleChar125TherapeutinRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/praxis': {
      id: '/{-$locale}/praxis'
      path: '/praxis'
      fullPath: '/{-$locale}/praxis'
      preLoaderRoute: typeof Char123LocaleChar125PraxisRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/podologie-urkunde': {
      id: '/{-$locale}/podologie-urkunde'
      path: '/podologie-urkunde'
      fullPath: '/{-$locale}/podologie-urkunde'
      preLoaderRoute: typeof Char123LocaleChar125PodologieUrkundeRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/podologie': {
      id: '/{-$locale}/podologie'
      path: '/podologie'
      fullPath: '/{-$locale}/podologie'
      preLoaderRoute: typeof Char123LocaleChar125PodologieRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/leistungen': {
      id: '/{-$locale}/leistungen'
      path: '/leistungen'
      fullPath: '/{-$locale}/leistungen'
      preLoaderRoute: typeof Char123LocaleChar125LeistungenRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/kontakt': {
      id: '/{-$locale}/kontakt'
      path: '/kontakt'
      fullPath: '/{-$locale}/kontakt'
      preLoaderRoute: typeof Char123LocaleChar125KontaktRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/hygiene': {
      id: '/{-$locale}/hygiene'
      path: '/hygiene'
      fullPath: '/{-$locale}/hygiene'
      preLoaderRoute: typeof Char123LocaleChar125HygieneRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/heilpraktiker-urkunde': {
      id: '/{-$locale}/heilpraktiker-urkunde'
      path: '/heilpraktiker-urkunde'
      fullPath: '/{-$locale}/heilpraktiker-urkunde'
      preLoaderRoute: typeof Char123LocaleChar125HeilpraktikerUrkundeRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/heilpraktiker-podologie': {
      id: '/{-$locale}/heilpraktiker-podologie'
      path: '/heilpraktiker-podologie'
      fullPath: '/{-$locale}/heilpraktiker-podologie'
      preLoaderRoute: typeof Char123LocaleChar125HeilpraktikerPodologieRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/chat': {
      id: '/{-$locale}/chat'
      path: '/chat'
      fullPath: '/{-$locale}/chat'
      preLoaderRoute: typeof Char123LocaleChar125ChatRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/anfahrt': {
      id: '/{-$locale}/anfahrt'
      path: '/anfahrt'
      fullPath: '/{-$locale}/anfahrt'
      preLoaderRoute: typeof Char123LocaleChar125AnfahrtRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads': {
      id: '/api/file-uploads'
      path: '/api/file-uploads'
      fullPath: '/api/file-uploads'
      preLoaderRoute: typeof ApiFileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads_/$fileUploadId': {
      id: '/api/file-uploads_/$fileUploadId'
      path: '/api/file-uploads/$fileUploadId'
      fullPath: '/api/file-uploads/$fileUploadId'
      preLoaderRoute: typeof ApiFileUploadsFileUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AnfahrtRoute: typeof Char123LocaleChar125AnfahrtRoute
  Char123LocaleChar125ChatRoute: typeof Char123LocaleChar125ChatRoute
  Char123LocaleChar125HeilpraktikerPodologieRoute: typeof Char123LocaleChar125HeilpraktikerPodologieRoute
  Char123LocaleChar125HeilpraktikerUrkundeRoute: typeof Char123LocaleChar125HeilpraktikerUrkundeRoute
  Char123LocaleChar125HygieneRoute: typeof Char123LocaleChar125HygieneRoute
  Char123LocaleChar125KontaktRoute: typeof Char123LocaleChar125KontaktRoute
  Char123LocaleChar125LeistungenRoute: typeof Char123LocaleChar125LeistungenRoute
  Char123LocaleChar125PodologieRoute: typeof Char123LocaleChar125PodologieRoute
  Char123LocaleChar125PodologieUrkundeRoute: typeof Char123LocaleChar125PodologieUrkundeRoute
  Char123LocaleChar125PraxisRoute: typeof Char123LocaleChar125PraxisRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125TherapeutinRoute: typeof Char123LocaleChar125TherapeutinRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AnfahrtRoute: Char123LocaleChar125AnfahrtRoute,
  Char123LocaleChar125ChatRoute: Char123LocaleChar125ChatRoute,
  Char123LocaleChar125HeilpraktikerPodologieRoute:
    Char123LocaleChar125HeilpraktikerPodologieRoute,
  Char123LocaleChar125HeilpraktikerUrkundeRoute:
    Char123LocaleChar125HeilpraktikerUrkundeRoute,
  Char123LocaleChar125HygieneRoute: Char123LocaleChar125HygieneRoute,
  Char123LocaleChar125KontaktRoute: Char123LocaleChar125KontaktRoute,
  Char123LocaleChar125LeistungenRoute: Char123LocaleChar125LeistungenRoute,
  Char123LocaleChar125PodologieRoute: Char123LocaleChar125PodologieRoute,
  Char123LocaleChar125PodologieUrkundeRoute:
    Char123LocaleChar125PodologieUrkundeRoute,
  Char123LocaleChar125PraxisRoute: Char123LocaleChar125PraxisRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125TherapeutinRoute: Char123LocaleChar125TherapeutinRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiFileUploadsRoute: ApiFileUploadsRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiFileUploadsFileUploadIdRoute: ApiFileUploadsFileUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
