/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125ChatRouteImport } from './routes/{-$locale}/chat'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as ApiFileUploadsRouteImport } from './routes/api/file-uploads'
import { Route as ApiFileUploadsFileUploadIdRouteImport } from './routes/api/file-uploads_.$fileUploadId'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ChatRoute =
  Char123LocaleChar125ChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsRoute = ApiFileUploadsRouteImport.update({
  id: '/api/file-uploads',
  path: '/api/file-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadsFileUploadIdRoute =
  ApiFileUploadsFileUploadIdRouteImport.update({
    id: '/api/file-uploads_/$fileUploadId',
    path: '/api/file-uploads/$fileUploadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/file-uploads': typeof ApiFileUploadsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125ChatRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/file-uploads_/$fileUploadId': typeof ApiFileUploadsFileUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/chat'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/api/file-uploads/$fileUploadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/chat'
    | '/{-$locale}/terms'
    | '/{-$locale}'
    | '/api/file-uploads/$fileUploadId'
  id:
    | '__root__'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/api/file-uploads'
    | '/api/graphql'
    | '/api/health'
    | '/api/stream'
    | '/{-$locale}/chat'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/api/file-uploads_/$fileUploadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiFileUploadsRoute: typeof ApiFileUploadsRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiFileUploadsFileUploadIdRoute: typeof ApiFileUploadsFileUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/chat': {
      id: '/{-$locale}/chat'
      path: '/chat'
      fullPath: '/{-$locale}/chat'
      preLoaderRoute: typeof Char123LocaleChar125ChatRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads': {
      id: '/api/file-uploads'
      path: '/api/file-uploads'
      fullPath: '/api/file-uploads'
      preLoaderRoute: typeof ApiFileUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-uploads_/$fileUploadId': {
      id: '/api/file-uploads_/$fileUploadId'
      path: '/api/file-uploads/$fileUploadId'
      fullPath: '/api/file-uploads/$fileUploadId'
      preLoaderRoute: typeof ApiFileUploadsFileUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125ChatRoute: typeof Char123LocaleChar125ChatRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125ChatRoute: Char123LocaleChar125ChatRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiFileUploadsRoute: ApiFileUploadsRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiFileUploadsFileUploadIdRoute: ApiFileUploadsFileUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
